### PR TITLE
check-updates: properly iterate over gitlab projects

### LINKED ISSUE #204: check-updates fails on this tback
```
[2021-05-11 22:13:54,380 updater.py DEBUG] Sending task 'task.dist2src.process_message', with payload: {'repo': {'fullname': 'rpms/vulkan-tools', 'name': 'vulkan-tools'}, 'branch': 'c8s', 'end_commit': 'abf10b9da1a00a94d8170946bccce1c934c6a627'}
[2021-05-11 22:13:54,386 updater.py INFO] Task UUID=cc49aa56-d1be-42aa-a3c2-c20140300e99 sent to Celery.
Traceback (most recent call last):
  File "/usr/local/bin/dist2src", line 11, in <module>
    load_entry_point('dist-git-to-source-git==0.1.dev1+gea9e62f.d20210511', 'console_scripts', 'dist2src')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 248, in check_updates
    Updater().check_updates(project, branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/worker/updater.py", line 73, in check_updates
    self._check_and_update_project(project_to_be_processed, branch=branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/worker/updater.py", line 87, in _check_and_update_project
    if not dist_git_project.exists():
  File "/usr/lib/python3.6/site-packages/ogr/services/pagure/project.py", line 326, in exists
    response = self._call_project_api_raw()
  File "/usr/lib/python3.6/site-packages/ogr/services/pagure/project.py", line 155, in _call_project_api_raw
    add_fork_part=add_fork_part,
  File "/usr/lib/python3.6/site-packages/ogr/services/pagure/project.py", line 171, in _get_project_url
    add_api_endpoint_part=add_api_endpoint_part,
  File "/usr/lib/python3.6/site-packages/ogr/services/pagure/service.py", line 226, in get_api_url
    return self.api_url + "/".join(args_list)
TypeError: sequence item 1: expected str instance, GroupProject found
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

### PR DESCRIPTION
**Pull request by TomasTomecek**
...in the second code-block

we should pass str's to _check_and_update_project, not GroupProject

Fix #204

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]

**Review by lbarcziova — APPROVED** [review]

**Comment by TomasTomecek** [comment]
I can't reproduce the test failures locally :x and there are no clear error messages in the logs, so...

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
the test failures caused by https://github.com/packit/packit/issues/1237

**Comment by TomasTomecek** [comment]
recheck

**Review by jpopelka — APPROVED** [review]

**Pull request merged**
