### PR TITLE
Do we want to run d2s with python3.8?

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by jpopelka** [comment]
I see only https://github.com/packit/dist-git-to-source-git/pull/32#issuecomment-675541977 which says "it's no longer happening", so why?

**Comment by TomasTomecek** [comment]
> I see only [#32 (comment)](https://github.com/packit/dist-git-to-source-git/pull/32#issuecomment-675541977) which says "it's no longer happening", so why?

because I did the work already so we can leave (and probably close) this here - we don't need to spend time on this again in future once we need this for sure - which will happen sooner or later, no real point in staying on 3.6 if we can have 3.8

**Comment by TomasTomecek** [comment]
closing then

**Comment by TomasTomecek** [comment]
and leaving the code here

**Pull request closed without merging**
