### PR TITLE
copy patches which are not applied during %prep

### PR DESCRIPTION
**Pull request by TomasTomecek**
because rpmbuild -bs needs those files - hence `packit srpm` fails

#57

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]
I like that we are copying the real patches and not some empty ones.

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
looks like a CI flake, since the first package install took ~20 minutes while it should take 2

> I like that we are copying the real patches and not some empty ones.

+1, originally I wanted to do empty ones but then realized that doesn't make any sense and with this, people can even develop patches for different arches, even though source-git won't be too helpful for them

**Comment by dhodovsk** [comment]
This one tracebacks for me with
```
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 455, in copy_conditional_patches
    file_src = self.dist_git_path / "SOURCES" / patch_name
  File "/usr/lib64/python3.6/pathlib.py", line 899, in __truediv__
    return self._make_child((key,))
  File "/usr/lib64/python3.6/pathlib.py", line 686, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not PatchObject
```
:(

**Comment by TomasTomecek** [comment]
Yes, it needs https://github.com/packit/packit/pull/972 forgot to add it to the description, sorry

I'm gonna install packit from master in the meantime.

**Comment by dhodovsk** [comment]
I have `RUN pip3 install --upgrade setuptools && pip3 install wheel && pip3 install git+https://github.com/packit/packit` added at the end of Containerfile and it still fails

**Comment by TomasTomecek** [comment]
@dhodovsk thanks, on it

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
Tomas' awesome local :beer: CI status: :green_heart: 
```
black....................................................................Passed
prettier.................................................................Passed
Check for added large files..............................................Passed
Check python ast.........................................................Passed
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
flake8...................................................................Passed
mypy.....................................................................Passed
Check if rebase is needed................................................Passed

=== 56 passed in 1803.78s (0:30:03) ===
```

**Comment by TomasTomecek** [comment]
> I have `RUN pip3 install --upgrade setuptools && pip3 install wheel && pip3 install git+https://github.com/packit/packit` added at the end of Containerfile and it still fails

I suspect that the stable packit was still being used despite you installing it from git master. I removed packitos from setup.cfg and it works now correctly, are we good to merge?

**Review by dhodovsk — APPROVED** [review]
Thank you, thank you, thank you! With this change, packages go through fine :)

**Pull request merged**
