### PR TITLE
tests: update old source-git repo with latest changes

### LINKED ISSUE #103: [source-git update] git cherry-pick fails due to staged changes
```
$ cd rpms; git clone https://git.centos.org/rpms/apr.git
$ cd ../source-git; git clone ssh://git@git.stg.centos.org/source-git/apr.git
$ cd ..; CONTAINER_CMD="dist2src -v convert rpms/apr:c8s source-git/apr:c8" make run
docker run \
	-ti --rm \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/dist2src:/usr/local/lib/python3.6/site-packages/dist2src:Z \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/packitpatch:/usr/bin/packitpatch:Z \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/macros.packit:/usr/lib/rpm/macros.d/macros.packit:Z \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/tests:/tests:Z \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/rpms:/workdir/rpms:Z \
	-v /home/jpopelka/git/packit/dist-git-to-source-git/source-git:/workdir/source-git:Z \
	-u 1000 \
	 \
	dist2src dist2src -v convert rpms/apr:c8s source-git/apr:c8
convert(origin='rpms/apr:c8s', dest='source-git/apr:c8')
Running command get_sources.sh in /workdir/rpms/apr
rpmbuild stderr = + umask 022
+ cd /workdir/rpms/apr/BUILD
+ cd /workdir/rpms/apr/BUILD
+ rm -rf apr-1.6.3
+ /usr/bin/bzip2 -dc /workdir/rpms/apr/SOURCES/apr-1.6.3.tar.bz2
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd apr-1.6.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/git init
+ /usr/bin/git add -f .
+ /usr/bin/git commit -q --allow-empty -a -m 'apr-1.6.3 base'
+ echo 'Patch #1 (apr-1.6.3-r1834495.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .r1834495 --fuzz=0
+ echo 'Patch #2 (apr-1.2.2-locktimeout.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .locktimeout --fuzz=0
+ echo 'Patch #3 (apr-1.2.2-libdir.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .libdir --fuzz=0
+ echo 'Patch #4 (apr-1.2.7-pkgconf.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .pkgconf --fuzz=0
+ echo 'Patch #5 (apr-rh1539844.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .rh1539844 --fuzz=0
+ echo 'Patch #6 (apr-1.4.8-deepbind.patch):'
+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .deepbind --fuzz=0
+ exit 0

The repo is not dirty, nothing to commit.
Fetch the dist-git %prep branch to source-git branch updates.
Traceback (most recent call last):
  File "/usr/local/bin/dist2src", line 33, in <module>
    sys.exit(load_entry_point('dist-git-to-source-git==0.1.dev218+g8cf46c8.d20201019', 'console_scripts', 'dist2src')())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 83, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dist2src/cli.py", line 226, in convert
    d2s.convert(origin_branch, dest_branch)
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 391, in convert
    from_branch=TEMP_SG_BRANCH, to_branch=dest_branch, theirs=update
  File "/usr/local/lib/python3.6/site-packages/dist2src/core.py", line 140, in cherry_pick_base
    self.repo.git.cherry_pick(f"{from_branch}~{num_commits - 1}", **git_options)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git cherry-pick updates~6
  stderr: 'error: your local changes would be overwritten by cherry-pick.
hint: commit your changes or stash them to proceed.
fatal: cherry-pick failed'
make: *** [Makefile:41: run] Error 1
```

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #103 (by providing a test case which passes)

@jpopelka sadly I wasn't able to reproduce, please let me know if the provided use case works on your laptop (I run it with `make check-in-container OPTS='-v /tmp:/tmp' TEST_TARGET='tests/test_update.py::test_update_apr'`

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]
Thanks!

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
the CI failure was a flake: pagure returned 404 for "units" even though it exists @_@

**Comment by TomasTomecek** [comment]
```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error
fatal: The remote end hung up unexpectedly
```
I give up for today.

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by TomasTomecek** [comment]
```
2020-10-22 06:49:15.963807 | container | [MIRROR] java-1.8.0-openjdk-devel-1.8.0.265.b01-0.el8_2.x86_64.rpm: Curl error (28): Timeout was reached for http://mirrors.tummy.com/mirrors/CentOS/8.2.2004/AppStream/x86_64/os/Packages/java-1.8.0-openjdk-devel-1.8.0.265.b01-0.el8_2.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
```

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
recheck

**Comment by jpopelka** [comment]
> please let me know if the provided use case works on your laptop

```
ERROR    dist2src.core:core.py:341 b"+ /usr/bin/git commit -q --allow-empty -a -m 'apr-1.6.3 base'"
ERROR    dist2src.core:core.py:341 b"+ echo 'Patch #1 (apr-1.6.3-r1834495.patch):'"
ERROR    dist2src.core:core.py:341 b"+ /usr/bin/packitpatch '%{1}' '%{2}' --fuzz=0 --no-backup-if-mismatch --no-backup-if-mismatch -p1 -b --suffix .r1834495 --fuzz=0"
ERROR    dist2src.core:core.py:341 b"/usr/bin/patch: **** Can't create temporary file /tmp/ppPSXFkc : Permission denied"
```

```
# setenforce 0
tests/test_update.py::test_update_apr PASSED
```

**Comment by TomasTomecek** [comment]
facepalm

**Pull request merged**
