### PR TITLE
readme: document why tests need to run in root containers

### PR DESCRIPTION
**Pull request by TomasTomecek**
https://github.com/packit/dist-git-to-source-git/pull/31#pullrequestreview-474268314

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]

**Review by lachmanfrantisek — COMMENTED** [review]
What about running `packit`/`mock` in the container as well?

I've just changed that locally and it works well. I'll send a PR. (#42 )

**Comment by lachmanfrantisek** [comment]
And btw, it's really painful that the tests are triggering the container engine. You can't run the tests in a container and need to have every packit dependency on the host and not everything can be installed via virtualenv.)

=> What about being able to run the whole test suite inside a container? (The `pytest` will run inside that container.)

**Comment by TomasTomecek** [comment]
> And btw, it's really painful that the tests are triggering the container engine. You can't run the tests in a container and need to have every packit dependency on the host and not everything can be installed via virtualenv.
> 
> => What about being able to run the whole test suite inside a container? (The `pytest` will run inside that container.)

Feel free to fix it :P

**Comment by lachmanfrantisek** [comment]
> Feel free to fix it :P

Done..;)  #43

**Pull request merged**
