### PR TITLE
[Containerfile] merge with files/Containerfile.worker

### LINKED ISSUE #114: Build conversion image in dockerhub and base worker image on it
As @csomh pointed out in #112, we should base the worker image on the one defined in [Containerfile](https://github.com/packit/dist-git-to-source-git/blob/d0510bd22879419871ab489e1ba51b18188c30e3/Containerfile) because it needs to install the same package-dependencies.

This conversion image is not built publicly like we are building the worker. The task of this issue is to:
- [ ] build the conversion image publicly
- [ ] base the worker image on the conversion one

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #114

### CODE REVIEW

**Review by TomasTomecek — APPROVED** [review]
LGTM, build passed for me

**Comment by jpopelka** [comment]
ugh, does the update kernel test ever pass? :-(

**Comment by csomh** [comment]
Is running `$package_manager clean all` after each install in order to clean the cache and avoid being backed into the final image still a thing? 

If this is required then probably it would make sense to merge all the `$package_manager` commands in a single RUN directive.

**Comment by jpopelka** [comment]
> probably it would make sense to merge all the `$package_manager` commands in a single RUN directive.

#130

**Pull request merged**
