### PR TITLE
Install-deps updates

### PR DESCRIPTION
**Pull request by jpopelka**
I'm just shuffling some bits around and hoping to shed some light on why `dist2src-deployment-tests` keeps failing in #186

### CODE REVIEW

**Comment by jpopelka** [comment]
And now the `dist2src-deployment-tests` failed even without those image changes from #186 so there's probably something unrelated broken (but where?)

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
With `-vvv` I can see:
```
17:04:21.422766 | test-node | Step 16/21 : RUN pip3 install -vvv . && pip3 check
17:04:22.841092 | test-node | Processing /src
17:04:22.947819 | test-node |   Running setup.py (path:/tmp/pip-hbwh21ml-build/setup.py) egg_info for package from file:///src
17:04:22.948264 | test-node |     Running command python setup.py egg_info
17:54:56.228632 | PRE-RUN END RESULT_TIMED_OUT: [untrusted : github.com/packit/dist-git-to-source-git/files/zuul-build-image.yml@main]
17:54:56.229033 | POST-RUN START: [trusted : github.com/packit/packit-service-zuul/playbooks/base/post.yaml@main]
```

which is not much more helpful.

**Review by TomasTomecek — APPROVED** [review]

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
recheck

**Review by TomasTomecek — APPROVED** [review]

**Pull request merged**
