### PR TITLE
Images are being moved from docker.io/usercont to quay.io/packit

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
recheck

**Comment by jpopelka** [comment]
>     dist2src-deployment-tests  : RETRY_LIMIT

I see some pypi retries, but don't understand it. It builds OK locally.

**Comment by TomasTomecek** [comment]
seems like it's still stuck :/

**Comment by jpopelka** [comment]
Comparing logs from the failed `dist2src-deployment-tests` here and successful one in #195 I see the pypi retries in both so it's unlikely a cause.

Failed:
```
18:24:18.873802 | test-node | Step 16/21 : RUN pip3 install . && pip3 check
18:24:20.623456 | test-node | Processing /src
19:11:13.835742 | PRE-RUN END RESULT_TIMED_OUT: [untrusted : github.com/packit/dist-git-to-source-git/files/zuul-build-image.yml@main]
19:11:13.840740 | POST-RUN START: [trusted : github.com/packit/packit-service-zuul/playbooks/base/post.yaml@main]
```
It was trying to pip install dist-git-to-source-git for 47minutes! and then timed out without a note.

Successful:
```
test-node | Requirement already satisfied: xyz
... (lots of requirements already satisfied)
test-node | Successfully installed click-7.1.2 dist-git-to-source-git-0.1.dev394+gc653705.d20210419 sh-1.14.1
```
in a couple of seconds.

I don't see how the change in this PR could be related. But why it always fails here and succeded in the #195?

**Comment by jpopelka** [comment]
Anytime (#196) I change the image in either of those files, the tests fail at the same place.
I give up, I don't get it, I don't see any relation.

**Comment by jpopelka** [comment]
Anyway, looks like someone already updated the deployment to use the Quay.io image:
```
$ oc describe is dist2src-centosmsg

latest
  updates automatically from registry quay.io/packit/packit-service-centosmsg:prod
```

**Review by TomasTomecek — APPROVED** [review]
It's a mystery to me as well.

**Pull request merged**
